// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "projectId": "studio-2085200026-82361",
  "appId": "1:338089395251:web:dbfac3f6233b656f4f4f46",
  "apiKey": "AIzaSyCSe9v6A8mspAJ5WwUYYVRV-4epHyadQmI",
  "authDomain": "studio-2085200026-82361.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "338089395251"
};
